//
//  MapRouter.swift
//  CurrentAddress
//
//  Created by Raymond Law on 7/20/17.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MapRoutingLogic
{
  func routeToPlacemark(segue: UIStoryboardSegue?)
}

protocol MapDataPassing
{
  var dataStore: MapDataStore? { get }
}

class MapRouter: NSObject, MapRoutingLogic, MapDataPassing
{
  weak var viewController: MapViewController?
  var dataStore: MapDataStore?
  
  // MARK: Routing
  
  func routeToPlacemark(segue: UIStoryboardSegue? = nil)
  {
    if let segue = segue {
      let destinationVC = segue.destination as! PlacemarkViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToPlacemark(source: dataStore!, destination: &destinationDS)
    } else {
      let storyboard = UIStoryboard(name: "MainStoryboard", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "PlacemarkViewController") as! PlacemarkViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToPlacemark(source: dataStore!, destination: &destinationDS)
      navigateToPlacemark(source: viewController!, destination: destinationVC)
    }
  }
  
  // MARK: Navigation
  
  private func navigateToPlacemark(source: MapViewController, destination: PlacemarkViewController)
  {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  private func passDataToPlacemark(source: MapDataStore, destination: inout PlacemarkDataStore)
  {
    destination.placemark = source.placemark
  }
}
