//
//  PlacemarkPresenterTests.swift
//  CurrentAddress
//
//  Created by Raymond Law on 8/3/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CurAddress
import XCTest

// MARK: - Test doubles

class PlacemarkDisplayLogicSpy: PlacemarkDisplayLogic
{
  var displayShowPhysicalAddressCalled = false
  
  func displayShowPhysicalAddress(viewModel: Placemark.ShowPhysicalAddress.ViewModel)
  {
    displayShowPhysicalAddressCalled = true
  }
}

class PlacemarkPresenterTests: XCTestCase
{
  // MARK: - Subject under test
  
  var sut: PlacemarkPresenter!
  
  // MARK: - Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupPlacemarkPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: - Test setup
  
  func setupPlacemarkPresenter()
  {
    sut = PlacemarkPresenter()
  }
  
  // MARK: - Tests
  
  // MARK: Show physical address
  
  func testPresentShowPhysicalAddress()
  {
    // Given
    let placemarkDisplayLogicSpy = PlacemarkDisplayLogicSpy()
    sut.viewController = placemarkDisplayLogicSpy
    let placemark = CurAddressTestHelpers.placemark
    let response = Placemark.ShowPhysicalAddress.Response(placemark: placemark)
    
    // When
    sut.presentShowPhysicalAddress(response: response)
    
    // Then
    XCTAssertTrue(placemarkDisplayLogicSpy.displayShowPhysicalAddressCalled, "presentShowPhysicalAddress() should ask the view controller to display the result")
  }
}
