//
//  PlacemarkViewControllerTests.swift
//  CurrentAddress
//
//  Created by Raymond Law on 8/3/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import CurAddress
import XCTest
import MapKit
import Contacts

// MARK: - Test doubles

class PlacemarkBusinessLogicSpy: PlacemarkBusinessLogic
{
  var showPhysicalAddressCalled = false
  
  func showPhysicalAddress(request: Placemark.ShowPhysicalAddress.Request)
  {
    showPhysicalAddressCalled = true
  }
}

class PlacemarkViewControllerTableViewSpy: UITableView
{
  var reloadSectionsCalled = false
  var reloadSectionsIndexSet: IndexSet?
  
  override func reloadSections(_ sections: IndexSet, with animation: UITableViewRowAnimation)
  {
    reloadSectionsCalled = true
    reloadSectionsIndexSet = sections
  }
}

class PlacemarkViewControllerTests: XCTestCase
{
  // MARK: - Subject under test
  
  var sut: PlacemarkViewController!
  var window: UIWindow!
  
  // MARK: - Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    window = UIWindow()
    setupPlacemarkViewController()
  }
  
  override func tearDown()
  {
    window = nil
    super.tearDown()
  }
  
  // MARK: - Test setup
  
  func setupPlacemarkViewController()
  {
    let bundle = Bundle.main
    let storyboard = UIStoryboard(name: "MainStoryboard", bundle: bundle)
    sut = storyboard.instantiateViewController(withIdentifier: "PlacemarkViewController") as! PlacemarkViewController
  }
  
  func loadView()
  {
    window.addSubview(sut.view)
    RunLoop.current.run(until: Date())
  }
  
  // MARK: - Tests
  
  // MARK: View lifecycle
  
  func testViewWillAppear()
  {
    // Given
    let placemarkBusinessLogicSpy = PlacemarkBusinessLogicSpy()
    sut.interactor = placemarkBusinessLogicSpy
    loadView()
    
    // When
    sut.viewWillAppear(true)
    
    // Then
    XCTAssertTrue(placemarkBusinessLogicSpy.showPhysicalAddressCalled, "viewWillAppear() should ask the interactor to show the physical address")
  }
  
  // MARK: Show physical address
  
  func testDisplayShowPhysicalAddressShouldConfigureCells()
  {
    // Given
    let placemarkBusinessLogicSpy = PlacemarkBusinessLogicSpy()
    sut.interactor = placemarkBusinessLogicSpy
    loadView()
    let placemark = CurAddressTestHelpers.placemark
    let viewModel = Placemark.ShowPhysicalAddress.ViewModel(placemark: placemark)
    
    // When
    sut.displayShowPhysicalAddress(viewModel: viewModel)
    
    // Then
    var cell = sut.tableView(sut.tableView, cellForRowAt: IndexPath(row: 0, section: 0))
    XCTAssertEqual(cell.detailTextLabel?.text, placemark.thoroughfare, "")
    
    cell = sut.tableView(sut.tableView, cellForRowAt: IndexPath(row: 1, section: 0))
    XCTAssertEqual(cell.detailTextLabel?.text, placemark.subThoroughfare, "")
    
    cell = sut.tableView(sut.tableView, cellForRowAt: IndexPath(row: 2, section: 0))
    XCTAssertEqual(cell.detailTextLabel?.text, placemark.locality, "")
    
    cell = sut.tableView(sut.tableView, cellForRowAt: IndexPath(row: 3, section: 0))
    XCTAssertEqual(cell.detailTextLabel?.text, placemark.subLocality, "")
    
    cell = sut.tableView(sut.tableView, cellForRowAt: IndexPath(row: 4, section: 0))
    XCTAssertEqual(cell.detailTextLabel?.text, placemark.administrativeArea, "")
    
    cell = sut.tableView(sut.tableView, cellForRowAt: IndexPath(row: 5, section: 0))
    XCTAssertEqual(cell.detailTextLabel?.text, placemark.subAdministrativeArea, "")
    
    cell = sut.tableView(sut.tableView, cellForRowAt: IndexPath(row: 6, section: 0))
    XCTAssertEqual(cell.detailTextLabel?.text, placemark.postalCode, "")
    
    cell = sut.tableView(sut.tableView, cellForRowAt: IndexPath(row: 7, section: 0))
    XCTAssertEqual(cell.detailTextLabel?.text, placemark.country, "")
    
    cell = sut.tableView(sut.tableView, cellForRowAt: IndexPath(row: 8, section: 0))
    XCTAssertEqual(cell.detailTextLabel?.text, placemark.isoCountryCode, "")
  }
  
  func testDisplayShowPhysicalAddressShouldReloadTableView()
  {
    // Given
    let placemarkBusinessLogicSpy = PlacemarkBusinessLogicSpy()
    sut.interactor = placemarkBusinessLogicSpy
    loadView()
    let placemarkViewControllerTableViewSpy = PlacemarkViewControllerTableViewSpy()
    sut.tableView = placemarkViewControllerTableViewSpy
    let viewModel = Placemark.ShowPhysicalAddress.ViewModel(placemark: CurAddressTestHelpers.placemark)
    
    // When
    sut.displayShowPhysicalAddress(viewModel: viewModel)
    
    // Then
    XCTAssertTrue(placemarkViewControllerTableViewSpy.reloadSectionsCalled, "")
    XCTAssertEqual(placemarkViewControllerTableViewSpy.reloadSectionsIndexSet, IndexSet(integer: 0), "")
  }
}
