//
//  PlacemarkRouter.swift
//  CurrentAddress
//
//  Created by Raymond Law on 7/20/17.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PlacemarkRoutingLogic
{
}

protocol PlacemarkDataPassing
{
  var dataStore: PlacemarkDataStore? { get }
}

class PlacemarkRouter: NSObject, PlacemarkRoutingLogic, PlacemarkDataPassing
{
  weak var viewController: PlacemarkViewController?
  var dataStore: PlacemarkDataStore?
  
  // MARK: Routing
  
  // MARK: Navigation
  
  // MARK: Passing data
}
