//
//  PlacemarkInteractor.swift
//  CurrentAddress
//
//  Created by Raymond Law on 7/20/17.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol PlacemarkBusinessLogic
{
  func showPhysicalAddress(request: Placemark.ShowPhysicalAddress.Request)
}

protocol PlacemarkDataStore
{
  var placemark: MKPlacemark! { get set }
}

class PlacemarkInteractor: PlacemarkBusinessLogic, PlacemarkDataStore
{
  var presenter: PlacemarkPresentationLogic?
  var worker: PlacemarkWorker?
  var placemark: MKPlacemark!
  
  // MARK: Show physical address
  
  func showPhysicalAddress(request: Placemark.ShowPhysicalAddress.Request)
  {
    let response = Placemark.ShowPhysicalAddress.Response(placemark: placemark)
    presenter?.presentShowPhysicalAddress(response: response)
  }
}
