//
//  PlacemarkPresenter.swift
//  CurrentAddress
//
//  Created by Raymond Law on 7/20/17.
//  Copyright (c) 2017 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlacemarkPresentationLogic
{
  func presentSomething(response: Placemark.Something.Response)
  func presentShowPhysicalAddress(response: Placemark.ShowPhysicalAddress.Response)
}

class PlacemarkPresenter: PlacemarkPresentationLogic
{
  weak var viewController: PlacemarkDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Placemark.Something.Response)
  {
    let viewModel = Placemark.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
  
  // MARK: Show physical address
  
  func presentShowPhysicalAddress(response: Placemark.ShowPhysicalAddress.Response)
  {
    let viewModel = Placemark.ShowPhysicalAddress.ViewModel(placemark: response.placemark)
    viewController?.displayShowPhysicalAddress(viewModel: viewModel)
  }
}
